root: true
env:
  node: true
parser: "@typescript-eslint/parser"
parserOptions:
  project: "./tsconfig.json"
plugins:
  - "@typescript-eslint"
  - "simple-import-sort"
  - "import"
extends:
  - "eslint:recommended"
  - "plugin:import/errors"
  - "plugin:import/warnings"
  - "plugin:@typescript-eslint/eslint-recommended"
  - "plugin:@typescript-eslint/recommended"
  - "plugin:prettier/recommended"
rules:
  simple-import-sort/imports:
    - "error"
  "@typescript-eslint/no-unused-vars":
    - "warn"
    - argsIgnorePattern: "^_"
settings:
  import/parsers:
    "@typescript-eslint/parser":
      - ".ts"
  import/resolver:
    typescript: {}
    node:
      extensions: [".js", ".jsx", ".ts", ".tsx"]
      paths:
        - "node_modules"
        - "src"
